- name: install python modules for ansible
  tags: setup
  apt: pkg=python-pycurl state=latest

- name: install curl
  tags: setup
  apt: pkg=curl state=latest

- name: php repo
  tags: setup
  apt_repository: repo='ppa:ondrej/php5' update_cache=yes

- name: install project dependencies
  apt: pkg={{ item }} state=latest
  tags: setup
  with_items:
    - nginx
    - php5
    - php5-common
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-mysql
    - php5-sqlite
    - php5-intl
    - supervisor
    - rabbitmq-server
