- name: update apt
  apt: update_cache=yes

- name: install python modules for ansible
  apt: pkg=python-pycurl state=latest

- name: install curl
  apt: pkg=curl state=latest

- name: install project dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - git
    - nginx
    - php5
    - php5-common
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-mysql
    - php5-sqlite
    - php5-intl
    - supervisor
    - rabbitmq-server
    - mysql-server

- name: configure fpm pool
  template: src=fpm.j2 dest="/etc/php5/fpm/pool.d/{{ project }}.conf"

- name: setup nginx vhost
  template: src=vhost.j2 dest="/etc/nginx/sites-available/{{ project }}"

- name: enable nginx vhost
  file: src=/etc/nginx/sites-available/{{ project }} path=/etc/nginx/sites-enabled/{{ project }} state=link

- name: restart nginx
  service: name=nginx state=restarted

- file: path=/etc/nginx/sites-enabled/default state=absent

- copy: src=server.crt dest=/srv/server.crt
- copy: src=server.key dest=/srv/server.key

- name: restart php5-fpm
  service: name=php5-fpm state=restarted

- name: configure rabbitmq vhost
  rabbitmq_vhost: name={{ project }} state=present

- name: configure rabbitmq user
  rabbitmq_user: user={{ project }}
                 password={{ project }}
                 vhost={{ project }}
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: install composer
  shell: >
    curl -sS https://getcomposer.org/installer | php;

- shell: mv composer.phar /usr/local/bin/composer;

- name: setup known_hosts
  copy: src=known_hosts dest=/etc/ssh/ssh_known_hosts

- service: name=nginx state=restarted